# Site settings
title: Geraint Ian Palmer
email: palmergi1@cardiff.ac.uk
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.geraintianpalmer.org.uk" # the base hostname & protocol for your site
github_username:  geraintpalmer
twitter_username: "@GeraintPalmer"

# Build settings
markdown: kramdown
permalink: pretty
syntax_highlighter: rouge

collections:
    teaching:
        output: true
    cv:
        output: true